- id: pyright
  name: pyright
  description: "Python checks using pyright"
  entry: pyright --warnings
  language: python
  types_or: [python]
  args: []
  require_serial: true
  additional_dependencies: []
  minimum_pre_commit_version: "2.9.2"
