[project]
name = "pyright-pre-commit"
version = "0.0.0"
dependencies = [
    "pyright==1.1.387",
]

[project.optional-dependencies]
dev = [
    "packaging~=23.1",
    "pip-tools>=7.3.0,<8.0.0",
    "urllib3>=2.0.5,<3.0.0",
]
